name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/usr/deploy/rust_blogger"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      env: 
        WEB_HOST: "0.0.0.0"
        WEB_PORT: "80"
        DB_HOST: "db"
        DB_PORT: "5432"
        DB_NAME: "rust_blogger"
        DB_USER: "postgres"
        DB_WAIT_TIME: "10"
        DB_URL: "postgres://postgres:${{ secrets.DB_PWD }}@db:5432/rust_blogger"
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}

        # Setup production environment     
        script: |
          cd /usr/deploy/rust_blogger
          echo WEB_HOST=${{ env.WEB_HOST }} >| .env
          echo WEB_PORT=${{ env.WEB_PORT }} >> .env
          echo DB_HOST=${{ env.DB_HOST }} >> .env
          echo DB_PORT=${{ env.DB_PORT }} >> .env
          echo DB_NAME=${{ env.DB_NAME }} >> .env
          echo DB_USER=${{ env.DB_USER }} >> .env
          echo DB_PWD=${{ secrets.DB_PWD }} >> .env 
          echo DB_WAIT_TIME=${{ env.DB_WAIT_TIME }} >> .env
          echo DB_URL=${{ env.DB_URL }} >> .env
          echo RUST_LOG=\"rust_blogger=info,actix_web=info\" >> .env